### ISSUE TITLE
failed to allocate a guard page

### ISSUE THREAD

**Issue by irevoire** [jfrimmel/cargo-valgrind#30]
Hello,

I'm trying to use this crate but it give me this error:
```
thread '<unnamed>' panicked at 'failed to allocate a guard page', src/libstd/sys/unix/thread.rs:336:17
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
fatal runtime error: failed to initiate panic, error 94375168
error: valgrind command failed
```

I'm using:
- FreeBSD 11.2
- rustc 1.39.0
- valgrind 3.10.1

**Comment by jfrimmel** [comment]
Hello,
can you please supply the following information:
1. is this reproducable
2. which crate are you analyzing
3. the whole command line used
4. The output of the run with `RUST_BACKTRACE=1`
Then I hope to fix that bug.

**Comment by irevoire** [comment]
Hello, sorry for the huge delay!

1. Yes it happens with everything
2. I can generate the bug with the hello world provided by cargo when you run `cargo new [name]`
3. `cargo valgrind`
4.
```
% export RUST_BACKTRACE=1
% cargo new hello
    Created binary (application) `hello` package
% cd hello
% cargo run
   Compiling hello v0.1.0 (/home/irevoire/hello)
    Finished dev [unoptimized + debuginfo] target(s) in 0.62s
     Running `target/debug/hello`
Hello, world!

% cargo valgrind
    Finished dev [unoptimized + debuginfo] target(s) in 0.02s
   Analyzing `target/debug/hello`
thread '<unnamed>' panicked at 'failed to allocate a guard page', src/libstd/sys/unix/thread.rs:336:17
stack backtrace:
   0: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
   1: core::fmt::write
   2: std::io::stdio::_print
   3: rust_oom
   4: rust_oom
   5: std::panicking::rust_panic_with_hook
   6: std::panicking::begin_panic_fmt
   7: std::rt::lang_start_internal
   8:
   9:
  10:
  11: <unknown>
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
fatal runtime error: failed to initiate panic, error 94376704
error: valgrind command failed
```

**Comment by irevoire** [comment]
This bug also happens with only valgrind so I’ll move this issue to the rust-lang repository.
